spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/portfolio?allowPublicKeyRetrieval=true&useSSL=false
    username: portfolio
    password: portfolio

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
